### ISSUE TITLE
Cannot retry failed jobs

### ISSUE THREAD

**Issue by razvanphp** [danhunsaker/php-resque#4]
I feel like this functionality is unfortunately not working, should be very useful. Every time we try to do this through resque-web by clicking on the `Retry Failed Jobs` we get this error on the php side:

```
ErrorException: Undefined index: id in /usr/share/nginx/www/backend/vendor/danhunsaker/php-resque/lib/Resque/Job.php:137
Stack trace:
#0 /usr/share/nginx/www/backend/vendor/danhunsaker/php-resque/lib/Resque/Job.php(137): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'Undefined index...', '/usr/share/ngin...', 137, Array)
#1 /usr/share/nginx/www/backend/vendor/danhunsaker/php-resque/lib/Resque/Worker.php(235): Resque_Job->getStatus()
#2 /usr/share/nginx/www/backend/vendor/hlgrrnhrdt/laravel-resque/src/Console/WorkCommand.php(69): Resque_Worker->work(5)
#3 /usr/share/nginx/www/backend/vendor/hlgrrnhrdt/laravel-resque/src/Console/WorkCommand.php(56): Hlgrrnhrdt\Resque\Console\WorkCommand->startWorker(Array, 5)
#4 [internal function]: Hlgrrnhrdt\Resque\Console\WorkCommand->fire()
#5 /usr/share/nginx/www/backend/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#6 /usr/share/nginx/www/backend/vendor/illuminate/console/Command.php(169): Illuminate\Container\Container->call(Array)
#7 /usr/share/nginx/www/backend/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /usr/share/nginx/www/backend/vendor/illuminate/console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /usr/share/nginx/www/backend/vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /usr/share/nginx/www/backend/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Hlgrrnhrdt\Resque\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /usr/share/nginx/www/backend/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /usr/share/nginx/www/backend/vendor/laravel/lumen-framework/src/Console/Kernel.php(76): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /usr/share/nginx/www/backend/artisan(43): Laravel\Lumen\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}
```

We use laravel and @Hlgrrnhrdt wrapper for php-resque, any idea what might have cause this?

Thank you!

**Comment by danhunsaker** [comment]
I can't tell which version of `danhunsaker/php-resque` you're using.  Line 137 in `lib/Resque/Job.php` is a comment in v1.3.2...

**Comment by razvanphp** [comment]
We're using `v1.3.1`, so it seems that the payload doesn't have the ID anymore..

`$status = new Resque_Job_Status($this->payload['id']);`

**Comment by danhunsaker** [comment]
I think 1.3.1 had a breaking bug of some kind...  I removed the tag from
GitHub...  Try updating to 1.3.2?

**Comment by razvanphp** [comment]
Hmm, we just tried, but it seems the psr version is hard pinned to the version `1.1.0` and this was not the case in `1.3.1`?

```
$ composer require hlgrrnhrdt/laravel-resque
Using version ^0.2.5 for hlgrrnhrdt/laravel-resque
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: psr/log[1.0.2, 1.0.0].
    - Can only install one of: psr/log[1.0.0, 1.0.2].
    - Can only install one of: psr/log[1.0.0, 1.0.2].
    - danhunsaker/php-resque v1.3.2 requires psr/log 1.0.0 -> satisfiable by psr/log[1.0.0].
    - hlgrrnhrdt/laravel-resque 0.2.5 requires danhunsaker/php-resque ^1.3 -> satisfiable by danhunsaker/php-resque[v1.3.2].
    - Installation request for hlgrrnhrdt/laravel-resque ^0.2.5 -> satisfiable by hlgrrnhrdt/laravel-resque[0.2.5].
    - Installation request for psr/log (locked at 1.0.2) -> satisfiable by psr/log[1.0.2].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by danhunsaker** [comment]
Oh my.  That's why I dropped 1.3.1 and 1.3.0....  I rebased the entire branch on upstream, and the commits to which 1.3.1 and 1.3.0 pointed no longer existed.  I know better than to do that...

I'll commit a 1.3.2.1 in just a moment to fix the `composer.json` for you.

**Comment by danhunsaker** [comment]
It's up.  Give that a shot.

**Comment by razvanphp** [comment]
Nice, it works now, at least bumping the version. Maybe this should also be a PR to upstream, there it's also hard pinned.

Now about the bug, can it be because we use `enqueueOnce` functionality? This is also the reason we don't get back to upstream master.

**Comment by danhunsaker** [comment]
I'm not sure.  If it still exists, I'd need the updated backtrace to say anything for sure.  I'm hoping it was just an artifact of my previous merge, and the rebase will clear a lot of that up.

**Comment by razvanphp** [comment]
Yes, still happens, here's the new stack trace:
```
ErrorException: Undefined index: id in /usr/share/nginx/www/backend/vendor/danhunsaker/php-resque/lib/Resque/Job.php:143
Stack trace:
#0 /usr/share/nginx/www/backend/vendor/danhunsaker/php-resque/lib/Resque/Job.php(143): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'Undefined index...', '/usr/share/ngin...', 143, Array)
#1 /usr/share/nginx/www/backend/vendor/danhunsaker/php-resque/lib/Resque/Worker.php(229): Resque_Job->getStatus()
#2 /usr/share/nginx/www/backend/vendor/hlgrrnhrdt/laravel-resque/src/Console/WorkCommand.php(69): Resque_Worker->work(5)
#3 /usr/share/nginx/www/backend/vendor/hlgrrnhrdt/laravel-resque/src/Console/WorkCommand.php(56): Hlgrrnhrdt\Resque\Console\WorkCommand->startWorker(Array, 5)
#4 [internal function]: Hlgrrnhrdt\Resque\Console\WorkCommand->fire()
#5 /usr/share/nginx/www/backend/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#6 /usr/share/nginx/www/backend/vendor/illuminate/console/Command.php(169): Illuminate\Container\Container->call(Array)
#7 /usr/share/nginx/www/backend/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /usr/share/nginx/www/backend/vendor/illuminate/console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /usr/share/nginx/www/backend/vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /usr/share/nginx/www/backend/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Hlgrrnhrdt\Resque\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /usr/share/nginx/www/backend/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /usr/share/nginx/www/backend/vendor/laravel/lumen-framework/src/Console/Kernel.php(76): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /usr/share/nginx/www/backend/artisan(43): Laravel\Lumen\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}
```

**Comment by danhunsaker** [comment]
OK, so it looks like Resque 2 (the Ruby version, which `resque-web` uses to interact with the queue(s)) doesn't include the `id` in the job any longer.  So when you requeue failed jobs from `resque-web`, they'll fail on any check for the job `id` back in `php-resque`.  The only fix is to roll back to an older Resque version - one where `id` is still used in the job data.

**Comment by razvanphp** [comment]
Ok, this is the explanation from my investigation too, but why can't we generate an ID when we encounter this situation instead of just throwing a fatal error?

**Comment by danhunsaker** [comment]
Given that this check is made at the *end* of the job's execution, generating an ID here doesn't make sense except as a workaround for this specific issue.  In other words, it's too brittle a fix.

I'm not sure (anymore) which version of Ruby Resque was current when PHP Resque was originally written, nor which revision removed use of the ID there, but rolling Resque Web back to somewhere in that range is the official response on how to handle this issue, as I recall.  Once things are moving again under the resque/php-resque repo, we'll be making some effort, I believe, to update the code such that it becomes compatible with the most recent version of Ruby's implementation again - at least so far as what's in Redis.  That'll mean IDs won't be expected, if they are even used any longer.

In the meantime, if you can't roll back to an earlier Resque Web that still generates (or at least preserves) IDs, I'd entertain a PR to check for and generate one when the job is initially pulled from Redis to be run (somewhere in or around the "reserve" method, if memory serves; check HOWITWORKS.md for exactly which methods are involved).  I don't think it's exactly the fix we'll really need to properly start playing catch-up, but it'll at least be a start, and much less brittle than making something up at the very end.
